/**:
  ros__parameters:
    # The length of the base link cube
    base_link_length: 0.5
    # The height from the platform to the ground
    platform_height: 1.5
    # The radius of the platform cylinder
    platform_cylinder_radius: 0.5
    # The height of the platform cylinder
    platform_cylinder_height: 0.05
    # The ratio: platform_connector_radius / platform_cylinder_radius
    platform_connector_radius_ratio: 0.1
    # The radius of the stem
    stem_radius: 0.1
    # The height of the stem
    stem_height: 0.05
    # The radius of the wheel
    wheel_radius: 0.2
    # The height of the wheel
    wheel_height: 0.1